// GENERATED FILE — DO NOT EDIT.
// Source: spec-bundle/pattern_like_astrology_app_data_source_registry_v0.2.yaml
// Regenerate: npm run generate:allowlist -w @patternlike/reading-engine
//
// A source enters reading assembly only if it appears here. Membership is
// `status != "excluded" AND phase != "never"`, which is strictly narrower than
// the `NO-*` id-prefix rule used by the D1 CHECKs: AMB-12 is excluded by status
// while carrying an ingestible prefix, so the prefix rule alone lets it through.

/** 25 of 139 registry sources are excluded; 1 of those (AMB-12) would survive a NO-* prefix check. */
export const EXCLUDED_BUT_NOT_NO_PREFIXED: readonly string[] = ["AMB-12"];

/** Every allowed_use token the registry defines. */
export const REGISTRY_ALLOWED_USE_VOCABULARY: readonly string[] = [
  "annual_context",
  "chart_fact",
  "consent_validation",
  "content_quality",
  "content_safety",
  "cycle_detection",
  "editorial_context",
  "editorial_research",
  "environment_context",
  "evidence_graph",
  "experimental_context",
  "feature_gating",
  "journal_import",
  "life_domain_selection",
  "local_day_boundary",
  "narrative_continuity",
  "notification_timing",
  "operational_delivery",
  "optional_recommendations",
  "optional_relocation_context",
  "pattern_profile",
  "product_quality",
  "product_research",
  "quality_audit",
  "recalculation_queue",
  "reflection_prompt",
  "relationship_interpretation",
  "rendering",
  "repetition_control",
  "reproducibility",
  "routine_context",
  "supportability",
  "sync_scheduling",
  "theme_eligibility",
  "theme_filtering",
  "theme_ranking",
  "time_travel",
  "timezone_resolution",
  "tone",
  "travel_context",
  "uncertainty_model",
  "user_memory",
  "weather_lookup",
  "workload_context",
];

/** Registry sources that may enter ingestion and reading assembly, with the
 *  exact uses each is permitted. An empty array means the source may be
 *  ingested but permits no interpretive use. */
export const INGESTIBLE_SOURCES: ReadonlyMap<string, readonly string[]> = new Map([
  ["AMB-01", ["environment_context", "notification_timing", "reflection_prompt"]],
  ["AMB-02", ["notification_timing", "operational_delivery"]],
  ["AMB-03", ["environment_context", "notification_timing", "reflection_prompt"]],
  ["AMB-04", ["notification_timing", "reflection_prompt", "tone"]],
  ["AMB-05", ["environment_context", "notification_timing", "reflection_prompt"]],
  ["AMB-06", ["environment_context", "notification_timing", "reflection_prompt"]],
  ["AMB-07", ["notification_timing", "reflection_prompt", "workload_context"]],
  ["AMB-08", ["optional_recommendations", "reflection_prompt"]],
  ["AMB-09", ["experimental_context", "product_research"]],
  ["AMB-10", ["quality_audit", "recalculation_queue"]],
  ["AMB-11", ["editorial_context", "theme_eligibility"]],
  ["AST-01", ["chart_fact", "cycle_detection", "uncertainty_model"]],
  ["AST-02", ["chart_fact", "timezone_resolution"]],
  ["AST-03", ["chart_fact", "cycle_detection", "uncertainty_model"]],
  ["AST-04", ["chart_fact", "cycle_detection", "theme_eligibility"]],
  ["AST-05", ["chart_fact", "life_domain_selection", "theme_eligibility"]],
  ["AST-06", ["chart_fact", "pattern_profile", "theme_eligibility"]],
  ["AST-07", ["pattern_profile", "theme_eligibility", "theme_ranking"]],
  ["AST-08", ["cycle_detection", "theme_eligibility", "theme_ranking"]],
  ["AST-09", ["cycle_detection", "narrative_continuity", "theme_eligibility"]],
  ["AST-10", ["cycle_detection", "theme_eligibility", "theme_ranking"]],
  ["AST-11", ["annual_context", "cycle_detection", "theme_eligibility"]],
  ["AST-12", ["annual_context", "theme_ranking", "time_travel"]],
  ["AST-13", ["annual_context", "theme_ranking"]],
  ["AST-14", ["cycle_detection", "narrative_continuity", "theme_eligibility"]],
  ["AST-15", ["cycle_detection", "theme_eligibility"]],
  ["AST-16", ["theme_eligibility", "theme_ranking"]],
  ["AST-17", ["relationship_interpretation", "theme_eligibility", "time_travel"]],
  ["AST-18", ["local_day_boundary", "optional_relocation_context"]],
  ["AST-19", ["notification_timing", "operational_delivery", "reflection_prompt"]],
  ["AST-20", ["evidence_graph", "quality_audit", "reproducibility"]],
  ["CLD-01", ["notification_timing", "reflection_prompt", "workload_context"]],
  ["CLD-02", ["notification_timing", "reflection_prompt", "workload_context"]],
  ["CLD-03", ["life_domain_selection", "reflection_prompt", "time_travel"]],
  ["CLD-04", ["notification_timing", "reflection_prompt", "workload_context"]],
  ["CLD-05", ["journal_import", "reflection_prompt", "user_memory"]],
  ["CLD-06", ["journal_import", "narrative_continuity", "user_memory"]],
  ["CLD-07", ["reflection_prompt", "time_travel"]],
  ["CLD-08", ["narrative_continuity", "reflection_prompt"]],
  ["CLD-09", ["narrative_continuity", "reflection_prompt"]],
  ["CLD-10", ["notification_timing", "routine_context", "tone"]],
  ["CLD-11", ["notification_timing", "routine_context", "tone"]],
  ["CLD-12", ["notification_timing", "routine_context", "tone"]],
  ["CLD-13", ["reflection_prompt", "routine_context"]],
  ["CLD-14", ["notification_timing", "workload_context"]],
  ["CLD-15", ["notification_timing", "workload_context"]],
  ["CLD-16", ["notification_timing", "workload_context"]],
  ["CLD-17", ["local_day_boundary", "notification_timing", "travel_context"]],
  ["CLD-18", ["relationship_interpretation", "time_travel"]],
  ["CLD-19", ["notification_timing", "reflection_prompt", "theme_ranking"]],
  ["CLD-20", ["consent_validation", "operational_delivery", "quality_audit"]],
  ["DER-01", ["narrative_continuity", "theme_eligibility", "tone"]],
  ["DER-02", ["theme_ranking"]],
  ["DER-03", ["evidence_graph", "theme_filtering", "uncertainty_model"]],
  ["DER-04", ["annual_context", "narrative_continuity", "theme_ranking"]],
  ["DER-05", ["notification_timing", "reflection_prompt", "tone"]],
  ["DER-06", ["notification_timing", "reflection_prompt"]],
  ["DER-07", ["notification_timing", "reflection_prompt", "tone"]],
  ["DER-08", ["notification_timing", "reflection_prompt"]],
  ["DER-09", ["notification_timing", "reflection_prompt", "tone"]],
  ["DER-10", ["notification_timing", "reflection_prompt"]],
  ["DER-11", ["narrative_continuity", "reflection_prompt", "theme_ranking"]],
  ["DER-12", ["repetition_control", "theme_ranking", "tone"]],
  ["DER-13", ["theme_filtering", "theme_ranking", "tone"]],
  ["DER-14", ["repetition_control", "theme_ranking"]],
  ["DER-15", ["evidence_graph", "quality_audit", "theme_filtering"]],
  ["DER-16", ["consent_validation", "operational_delivery"]],
  ["DER-17", ["evidence_graph", "reproducibility", "supportability"]],
  ["DER-18", ["theme_eligibility", "theme_ranking"]],
  ["DER-19", ["notification_timing"]],
  ["DER-20", ["product_quality", "quality_audit"]],
  ["DER-21", ["evidence_graph", "theme_filtering"]],
  ["DER-22", ["content_safety", "quality_audit"]],
  ["DEV-01", ["local_day_boundary", "notification_timing", "rendering"]],
  ["DEV-02", ["local_day_boundary", "optional_relocation_context", "weather_lookup"]],
  ["DEV-03", ["notification_timing", "reflection_prompt", "routine_context"]],
  ["DEV-04", ["notification_timing", "reflection_prompt", "workload_context"]],
  ["DEV-05", ["notification_timing", "reflection_prompt", "workload_context"]],
  ["DEV-06", ["narrative_continuity", "reflection_prompt", "time_travel"]],
  ["DEV-07", ["reflection_prompt", "time_travel"]],
  ["DEV-08", ["notification_timing", "routine_context"]],
  ["DEV-09", ["notification_timing", "routine_context", "tone"]],
  ["DEV-10", ["notification_timing", "reflection_prompt", "tone"]],
  ["DEV-11", ["narrative_continuity", "reflection_prompt"]],
  ["DEV-12", ["notification_timing", "routine_context"]],
  ["DEV-13", ["notification_timing", "reflection_prompt", "tone"]],
  ["DEV-14", ["notification_timing", "operational_delivery", "quality_audit"]],
  ["DEV-15", ["environment_context", "reflection_prompt"]],
  ["DEV-16", ["operational_delivery", "sync_scheduling"]],
  ["DEV-17", ["operational_delivery", "rendering"]],
  ["USR-01", ["life_domain_selection", "theme_ranking"]],
  ["USR-02", ["life_domain_selection", "reflection_prompt", "theme_ranking"]],
  ["USR-03", ["life_domain_selection", "reflection_prompt", "theme_ranking"]],
  ["USR-04", ["reflection_prompt", "rendering", "tone"]],
  ["USR-05", ["notification_timing", "theme_filtering"]],
  ["USR-06", ["notification_timing", "reflection_prompt", "theme_ranking", "tone"]],
  ["USR-07", ["narrative_continuity", "reflection_prompt", "theme_ranking"]],
  ["USR-08", ["life_domain_selection", "reflection_prompt", "theme_ranking"]],
  ["USR-09", ["narrative_continuity", "theme_ranking", "time_travel"]],
  ["USR-10", ["narrative_continuity", "reflection_prompt", "user_memory"]],
  ["USR-11", ["life_domain_selection", "narrative_continuity", "theme_ranking"]],
  ["USR-12", ["content_quality", "repetition_control", "theme_ranking"]],
  ["USR-13", ["content_quality", "life_domain_selection", "theme_ranking"]],
  ["USR-14", ["content_quality", "repetition_control", "theme_ranking"]],
  ["USR-15", ["notification_timing", "theme_filtering", "theme_ranking"]],
  ["USR-16", ["chart_fact", "quality_audit", "uncertainty_model"]],
  ["USR-17", ["notification_timing", "operational_delivery"]],
  ["USR-18", ["relationship_interpretation", "time_travel"]],
  ["USR-19", ["life_domain_selection", "reflection_prompt", "tone"]],
  ["USR-20", ["narrative_continuity", "reflection_prompt", "time_travel"]],
  ["USR-21", ["operational_delivery", "rendering"]],
  ["USR-22", ["feature_gating", "operational_delivery"]],
  ["USR-23", ["quality_audit", "supportability"]],
  ["USR-24", ["editorial_research", "product_quality"]],
]);

export const REGISTRY_SOURCE_COUNT = 139;
export const INGESTIBLE_SOURCE_COUNT = 114;
