name = "patternlike-ontology-signer"
main = "src/index.ts"
compatibility_date = "2025-05-01"
workers_dev = false
preview_urls = false

[env.production]
name = "patternlike-ontology-signer-production"
workers_dev = false
preview_urls = false
