/**
 * The provider-neutral publisher boundary and its configuration.
 *
 * The adapter behind this interface owns exactly one thing: turning a closed
 * request into a candidate or a typed failure. Consent, context selection,
 * astrology policy, retry classification, budget, publication, and logging all
 * stay in the Worker. That division is what lets the provider be replaced
 * without touching anything that decides what a reader is allowed to see.
 *
 * Every configured value below is pinned to the exact number the code was
 * written for rather than merely parsed. "The model is whatever the var says" is
 * how a deployment silently starts publishing prose that the frozen input never
 * described, and the same argument applies to the timeout the lease arithmetic
 * assumes and the ceilings the packet compiler enforces.
 */

import type {
  ReadingGenerationOutput,
  ReadingGenerationRequest,
  ReadingPublisherProvider,
} from "@patternlike/shared";
import {
  SELECTION_POLICY_VERSION,
  VALIDATION_POLICY_VERSION,
} from "@patternlike/reading-engine";
import type { Env } from "../env.js";
import { readReadingV5Rollout, type ReadingV5Rollout } from "./reading-rollout.js";

// ---------------------------------------------------------------------------
// Pinned configuration
// ---------------------------------------------------------------------------

/**
 * The one live Daily publisher.
 *
 * Daily generation runs through the durable Codex CLI runner and has no
 * fallback: no direct OpenAI transport, no Workers AI, no synthetic publisher
 * outside development fixtures. A live deployment naming anything else is a
 * configuration error rather than a degraded mode, because "degraded" here
 * would mean publishing a reader's prose through a path nobody reviewed.
 *
 * `openai` remains in the shared M5 vocabulary and in stored evidence. It is
 * the publisher that historical readings were generated by, not one this
 * deployment can select.
 */
export const READING_PUBLISHER_PROVIDER = "codex" as const;

/**
 * The exact production model.
 *
 * The `OPENAI_READING_*` names are model-family pins, kept because renaming a
 * deployed variable is cleanup rather than a prerequisite. They are NOT
 * evidence of direct API routing: the request reaches this model through the
 * Codex runner, and nothing in this Worker holds an OpenAI credential for
 * Daily.
 */
export const OPENAI_READING_MODEL = "gpt-5.6-sol";
export const OPENAI_READING_REASONING = "high" as const;
/**
 * The runner's deadline, not a Worker's.
 *
 * Ninety seconds was what a synchronous provider call could afford inside a
 * five-minute Queue lease. The external call no longer runs inside that lease
 * at all — the executor returns the Daily job to `queued(publisher_pending)`
 * and releases it — so this is the Codex contract's own ceiling.
 */
export const OPENAI_READING_TIMEOUT_MS = 900_000;
export const OPENAI_READING_MAX_OUTPUT_TOKENS = 4000;
export const READING_CONTEXT_MAX_BYTES = 98_304;
export const READING_PREGEN_ACTIVE_DAYS = 30;
export const READING_PREGEN_LEAD_MINUTES = 30;
export const READING_PREGEN_SPREAD_MINUTES = 45;
export const READING_SCHEDULER_BATCH_LIMIT = 100;

/** The provider endpoint, used when no AI Gateway is configured. */
export const OPENAI_RESPONSES_URL = "https://api.openai.com/v1/responses";

/**
 * The AI Gateway origin, when `AI_GATEWAY_ACCOUNT_ID` and `AI_GATEWAY_ID` name
 * a gateway to route through.
 *
 * Provider-native, not the unified `/compat/chat/completions` endpoint and not
 * the `api.cloudflare.com` REST API. Both of those speak Chat Completions, and
 * this adapter reads the Responses envelope — `output` items, refusal parts,
 * `incomplete_details`. A reshaped response would not fail loudly: it would
 * turn every publish into `missing_output_text`.
 *
 * The route is deliberately NOT part of `PublisherConfigPin`. A proxy in front
 * of the same Responses API with the same model, prompt version, and ceilings
 * describes the same prose, so a command frozen before the gateway existed is
 * still honestly described after it.
 */
export const AI_GATEWAY_ORIGIN = "https://gateway.ai.cloudflare.com";

/**
 * A resolved gateway route.
 *
 * `token` is the `cf-aig-authorization` credential, needed only while the
 * gateway has Authenticated Gateway switched on. It is not the provider key:
 * the OpenAI key still rides `Authorization`, which the gateway forwards.
 */
export interface AiGatewayRoute {
  accountId: string;
  gatewayId: string;
  token: string | null;
}

export type AiGatewayOutcome =
  | { ok: true; route: AiGatewayRoute | null }
  | { ok: false; message: string };

/** 32 lowercase hex characters, which is what a Cloudflare account id is. */
const AI_GATEWAY_ACCOUNT_ID_PATTERN = /^[0-9a-f]{32}$/;
/** One path segment, and unambiguously one: no dot, no slash, no escape. */
const AI_GATEWAY_ID_PATTERN = /^[a-z0-9][a-z0-9_-]{0,63}$/;

/**
 * Resolve the gateway route, or its absence.
 *
 * Shape is checked rather than trusted because both values are interpolated
 * into a URL path. Refusing a malformed id here is what keeps `responsesUrlFor`
 * total: it can only ever return the direct endpoint or a well-formed gateway
 * one, never a URL assembled from whatever a var happened to contain.
 *
 * Half-configured is an error rather than a fallback. An operator who set one
 * of the two ids meant to route through a gateway, and silently continuing to
 * bill and log against the provider directly is the opposite of what they
 * asked for — it would look like a working deployment with an empty dashboard.
 */
export function resolveAiGatewayRoute(env: Partial<Env>): AiGatewayOutcome {
  const accountId = env.AI_GATEWAY_ACCOUNT_ID?.trim() ?? "";
  const gatewayId = env.AI_GATEWAY_ID?.trim() ?? "";
  const token = env.AI_GATEWAY_TOKEN?.trim() ?? "";

  if (accountId === "" && gatewayId === "") {
    if (token !== "") {
      return {
        ok: false,
        message:
          "AI_GATEWAY_TOKEN is set without AI_GATEWAY_ACCOUNT_ID and AI_GATEWAY_ID",
      };
    }
    return { ok: true, route: null };
  }
  if (accountId === "" || gatewayId === "") {
    return {
      ok: false,
      message: "AI_GATEWAY_ACCOUNT_ID and AI_GATEWAY_ID must be set together",
    };
  }
  if (!AI_GATEWAY_ACCOUNT_ID_PATTERN.test(accountId)) {
    return {
      ok: false,
      message: "AI_GATEWAY_ACCOUNT_ID must be 32 lowercase hexadecimal characters",
    };
  }
  if (!AI_GATEWAY_ID_PATTERN.test(gatewayId)) {
    return {
      ok: false,
      message:
        "AI_GATEWAY_ID must be one path segment of lowercase letters, digits, - or _",
    };
  }
  return {
    ok: true,
    route: { accountId, gatewayId, token: token === "" ? null : token },
  };
}


// ---------------------------------------------------------------------------
// Provider credential mode
// ---------------------------------------------------------------------------

/**
 * How this deployment authenticates to OpenAI.
 *
 * `worker` sends the Worker's own key as `Authorization`. `gateway_stored`
 * sends NO provider `Authorization` at all and names a stored key by alias, so
 * AI Gateway supplies the credential from BYOK.
 *
 * The distinction is load-bearing, not cosmetic. On a provider-native request a
 * key on the request has FIRST precedence: AI Gateway forwards it and never
 * consults the stored key. So a deployment that means to use BYOK but still
 * sends `Authorization` silently bypasses the stored key -- and rotating the
 * gateway-stored key would appear to succeed while every request kept using the
 * Worker secret.
 */
export type ProviderCredentialMode =
  | { source: "worker"; apiKey: string }
  | { source: "gateway_stored"; alias: string };

export type ProviderCredentialOutcome =
  | { ok: true; mode: ProviderCredentialMode }
  | { ok: false; message: string };

export const OPENAI_CREDENTIAL_SOURCES = ["worker", "gateway_stored"] as const;

/**
 * Resolve the credential mode, or refuse.
 *
 * Selected by an explicit variable and NEVER inferred from whether
 * `OPENAI_API_KEY` happens to be set: inference cannot tell "the stored key is
 * in use" from "the worker key was forgotten", and those two need opposite
 * outcomes -- one is correct, the other must refuse to serve.
 *
 * Every refusal names the conflicting variables and never their values.
 */
export function resolveProviderCredentialMode(
  env: Partial<Env>,
  route: AiGatewayRoute | null,
): ProviderCredentialOutcome {
  const source = env.OPENAI_CREDENTIAL_SOURCE?.trim() ?? "";
  const apiKey = env.OPENAI_API_KEY?.trim() ?? "";
  const alias = env.OPENAI_GATEWAY_KEY_ALIAS?.trim() ?? "";

  if (source === "") {
    return { ok: false, message: "OPENAI_CREDENTIAL_SOURCE is required when a rollout is enabled" };
  }
  if (!(OPENAI_CREDENTIAL_SOURCES as readonly string[]).includes(source)) {
    return { ok: false, message: "OPENAI_CREDENTIAL_SOURCE must be worker or gateway_stored" };
  }

  if (source === "worker") {
    if (apiKey === "") {
      return { ok: false, message: "OPENAI_API_KEY is required when OPENAI_CREDENTIAL_SOURCE=worker" };
    }
    // Today's behaviour exactly. The direct path and the live reading rollout
    // are unaffected by this task.
    return { ok: true, mode: { source: "worker", apiKey } };
  }

  // A stored key only exists behind a gateway.
  if (route === null) {
    return {
      ok: false,
      message:
        "OPENAI_CREDENTIAL_SOURCE=gateway_stored requires AI_GATEWAY_ACCOUNT_ID and AI_GATEWAY_ID",
    };
  }
  // BYOK's prerequisite is an authenticated gateway. Discovering this as an
  // ambiguous 401 in the middle of a generation is far too late.
  if (route.token === null) {
    return {
      ok: false,
      message: "OPENAI_CREDENTIAL_SOURCE=gateway_stored requires AI_GATEWAY_TOKEN",
    };
  }
  // Refused rather than tolerated: a request key wins over BYOK, so accepting
  // both would silently bypass the stored alias this mode exists to use.
  if (apiKey !== "") {
    return {
      ok: false,
      message: "OPENAI_API_KEY must not be set when OPENAI_CREDENTIAL_SOURCE=gateway_stored",
    };
  }
  // Pinned explicitly rather than left to the implicit `default` alias: adding a
  // second stored key later would otherwise change nothing until somebody
  // noticed which one `default` pointed at.
  if (alias === "") {
    return {
      ok: false,
      message: "OPENAI_GATEWAY_KEY_ALIAS is required when OPENAI_CREDENTIAL_SOURCE=gateway_stored",
    };
  }
  return { ok: true, mode: { source: "gateway_stored", alias } };
}

/**
 * The Responses endpoint for a route, or the direct one for `null`.
 *
 * Note the path. AI Gateway's base URL replaces `https://api.openai.com/v1`
 * whole, so the Responses endpoint is `…/openai/responses`. `…/openai/v1/
 * responses` is a 404, and a 404 is the one status this adapter reads as
 * `publisher_model_unavailable` — a terminal failure blaming the model for a
 * mistyped URL.
 */
export function responsesUrlFor(route: AiGatewayRoute | null): string {
  if (route === null) return OPENAI_RESPONSES_URL;
  return `${AI_GATEWAY_ORIGIN}/v1/${route.accountId}/${route.gatewayId}/openai/responses`;
}

/**
 * The deployed prompt contract. Bump for ANY wording change.
 *
 * Lives here rather than beside the prompt so `resolvePublisherConfiguration`
 * can pin the deployed variable against it without a circular import;
 * `reading-prompt.ts` re-exports it, so every caller still reads it from there.
 */
export const READING_PROMPT_VERSION = "1.0.1";

// ---------------------------------------------------------------------------
// Frozen configuration pin
// ---------------------------------------------------------------------------

/**
 * The exact publisher configuration a claimed job must use, frozen at enqueue.
 *
 * Execution passes this to the adapter instead of rereading the environment: a
 * model or prompt change between enqueue and claim would otherwise publish
 * prose under an identity that promises different prose.
 */
export interface PublisherConfigPin {
  /**
   * The frozen publisher, which is the shared closed vocabulary rather than
   * today's configured one. A command frozen under the direct OpenAI transport
   * must remain describable — and, crucially, distinguishable — after the live
   * publisher became Codex; the executor refuses to run one under the other.
   */
  provider: ReadingPublisherProvider;
  model: string;
  reasoning_effort: "low" | "medium" | "high";
  prompt_version: string;
  output_schema: "daily-reading-v5";
  selection_policy_version: string;
  validation_policy_version: string;
  max_output_tokens: number;
  context_max_bytes: number;
}

/**
 * No `credential` field, deliberately.
 *
 * Daily reaches its model through the Codex runner, which authenticates to the
 * Worker rather than the other way round. A resolved credential here would be a
 * value some later call site could read as permission to open a direct
 * connection, and the whole point of the move is that no such connection
 * exists.
 */
export interface PublisherConfig {
  pin: PublisherConfigPin;
  timeoutMs: number;
  dailyCallLimit: number;
  pregenActiveDays: number;
  pregenLeadMinutes: number;
  pregenSpreadMinutes: number;
  schedulerBatchLimit: number;
}

export type PublisherConfigOutcome =
  | { ok: true; rollout: ReadingV5Rollout; config: PublisherConfig | null }
  | { ok: false; code: "reading_rollout_invalid" | "reading_publisher_misconfigured"; message: string };

// ---------------------------------------------------------------------------
// Provider result
// ---------------------------------------------------------------------------

/**
 * The failure vocabulary lives in `openai-responses-adapter.ts` so readings and
 * Patterns cannot drift apart on it. Re-exported here because this module is
 * where every existing caller reads it from, and a type-only re-export is
 * erased at build time — so the value edge stays one-way, adapter to here.
 */
import type {
  PublisherFailureCode,
  PublisherSafeDetailCode,
} from "./openai-responses-adapter.js";

export type {
  PublisherFailureCode,
  PublisherSafeDetailCode,
  PublisherFailure,
} from "./openai-responses-adapter.js";

export interface ProviderMetadata {
  provider: ReadingPublisherProvider;
  model: string;
  provider_request_id: string;
  input_tokens: number;
  output_tokens: number;
  /** Digest of the exact response bytes, taken before they were discarded. */
  provider_response_hash: string;
}

export type PublisherResult =
  | { ok: true; candidate: ReadingGenerationOutput; metadata: ProviderMetadata }
  | {
      ok: false;
      code: PublisherFailureCode;
      safe_detail_code: PublisherSafeDetailCode;
      retry_after_seconds: number | null;
    };

export interface PublishOptions {
  /** The Worker's own correlation id. Never sent to the provider. */
  requestId: string;
  timeoutMs: number;
  configuration: PublisherConfigPin;
}

export interface ReadingPublisher {
  publish(
    request: ReadingGenerationRequest,
    options: PublishOptions,
  ): Promise<PublisherResult>;
}

// ---------------------------------------------------------------------------
// Configuration resolution
// ---------------------------------------------------------------------------

function misconfigured(message: string): PublisherConfigOutcome {
  return { ok: false, code: "reading_publisher_misconfigured", message };
}

/** An exact integer, or null. A float or a non-numeric string is not "close enough". */
function readInteger(value: string | undefined): number | null {
  if (value === undefined) return null;
  const trimmed = value.trim();
  if (!/^-?\d+$/.test(trimmed)) return null;
  const parsed = Number(trimmed);
  return Number.isSafeInteger(parsed) ? parsed : null;
}

/** A value that is pinned to one number, checked whether or not it is required. */
function checkPinnedInteger(
  raw: string | undefined,
  expected: number,
  key: string,
): string | null {
  if (raw === undefined || raw.trim() === "") return null;
  const parsed = readInteger(raw);
  if (parsed === null) return `${key} must be an integer`;
  if (parsed !== expected) return `${key} must be exactly ${expected}`;
  return null;
}

/**
 * Resolve the rollout and, when it is not `off`, the complete publisher
 * configuration.
 *
 * The `off` branch is a real state rather than a half-configured one: the
 * schema-compatible deploy that lands the dual readers carries no publisher
 * variables and no key at all and must still serve every existing surface. A
 * value that IS present is validated regardless of the mode, so a typo does not
 * lie dormant until the day someone enables the feature.
 */
export function resolvePublisherConfiguration(
  env: Partial<Env>,
): PublisherConfigOutcome {
  const rollout = readReadingV5Rollout(env);
  if (rollout === null) {
    return {
      ok: false,
      code: "reading_rollout_invalid",
      message:
        "READING_V5_ROLLOUT must be one of off, internal, first_open, or hybrid",
    };
  }

  const pinned: Array<[string | undefined, number, string]> = [
    [env.OPENAI_READING_TIMEOUT_MS, OPENAI_READING_TIMEOUT_MS, "OPENAI_READING_TIMEOUT_MS"],
    [
      env.OPENAI_READING_MAX_OUTPUT_TOKENS,
      OPENAI_READING_MAX_OUTPUT_TOKENS,
      "OPENAI_READING_MAX_OUTPUT_TOKENS",
    ],
    [env.READING_CONTEXT_MAX_BYTES, READING_CONTEXT_MAX_BYTES, "READING_CONTEXT_MAX_BYTES"],
    [env.READING_PREGEN_ACTIVE_DAYS, READING_PREGEN_ACTIVE_DAYS, "READING_PREGEN_ACTIVE_DAYS"],
    [env.READING_PREGEN_LEAD_MINUTES, READING_PREGEN_LEAD_MINUTES, "READING_PREGEN_LEAD_MINUTES"],
    [
      env.READING_PREGEN_SPREAD_MINUTES,
      READING_PREGEN_SPREAD_MINUTES,
      "READING_PREGEN_SPREAD_MINUTES",
    ],
    [
      env.READING_SCHEDULER_BATCH_LIMIT,
      READING_SCHEDULER_BATCH_LIMIT,
      "READING_SCHEDULER_BATCH_LIMIT",
    ],
  ];
  for (const [raw, expected, key] of pinned) {
    const problem = checkPinnedInteger(raw, expected, key);
    if (problem) return misconfigured(problem);
  }

  // Checked with the pinned values rather than with the required ones: the
  // gateway is optional in every mode, so there is nothing to demand — but a
  // value that IS present and malformed must fail here, where the answer is a
  // 503 on the next request, rather than at the fetch, where it is a reading
  // that failed for a reason no failure class describes.
  const gateway = resolveAiGatewayRoute(env);
  if (!gateway.ok) return misconfigured(gateway.message);

  const publisher = env.READING_PUBLISHER?.trim();
  if (publisher !== undefined && publisher !== "" && publisher !== READING_PUBLISHER_PROVIDER) {
    return misconfigured("READING_PUBLISHER must be codex");
  }
  const model = env.OPENAI_READING_MODEL?.trim();
  if (model !== undefined && model !== "" && model !== OPENAI_READING_MODEL) {
    return misconfigured("OPENAI_READING_MODEL must be the exact preflight-approved model");
  }
  const reasoning = env.OPENAI_READING_REASONING?.trim();
  if (reasoning !== undefined && reasoning !== "" && reasoning !== OPENAI_READING_REASONING) {
    return misconfigured("OPENAI_READING_REASONING must be high");
  }
  const callLimitRaw = env.READING_DAILY_PROVIDER_CALL_LIMIT?.trim();
  let callLimit: number | null = null;
  if (callLimitRaw !== undefined && callLimitRaw !== "") {
    callLimit = readInteger(callLimitRaw);
    if (callLimit === null) {
      return misconfigured("READING_DAILY_PROVIDER_CALL_LIMIT must be an integer");
    }
    if (callLimit < 1) {
      return misconfigured(
        "READING_DAILY_PROVIDER_CALL_LIMIT must be a positive operator-approved ceiling",
      );
    }
  }

  if (rollout === "off") return { ok: true, rollout, config: null };

  const promptVersion = env.OPENAI_READING_PROMPT_VERSION?.trim();
  // Pinned like every other member of the tuple. Presence alone was not enough:
  // the execute path demands equality with the compiled constant, and it only
  // gets there after the pending reading row is reserved and the job committed —
  // where the mismatch is `policy_unsupported`, which is terminal and NOT
  // automatically replaceable. A prompt bump that misses the deployed variable
  // would 424 every reading for every user until an operator noticed. Refusing
  // here turns that into 503 configuration_error on the first request instead.
  if (promptVersion !== undefined && promptVersion !== "" && promptVersion !== READING_PROMPT_VERSION) {
    return misconfigured(
      "OPENAI_READING_PROMPT_VERSION must be the exact compiled prompt version",
    );
  }
  const required: Array<[unknown, string]> = [
    [publisher, "READING_PUBLISHER"],
    [model, "OPENAI_READING_MODEL"],
    [reasoning, "OPENAI_READING_REASONING"],
    [promptVersion, "OPENAI_READING_PROMPT_VERSION"],
    [env.OPENAI_READING_TIMEOUT_MS?.trim(), "OPENAI_READING_TIMEOUT_MS"],
    [env.OPENAI_READING_MAX_OUTPUT_TOKENS?.trim(), "OPENAI_READING_MAX_OUTPUT_TOKENS"],
    [env.READING_CONTEXT_MAX_BYTES?.trim(), "READING_CONTEXT_MAX_BYTES"],
    [env.READING_PREGEN_ACTIVE_DAYS?.trim(), "READING_PREGEN_ACTIVE_DAYS"],
    [env.READING_PREGEN_LEAD_MINUTES?.trim(), "READING_PREGEN_LEAD_MINUTES"],
    [env.READING_PREGEN_SPREAD_MINUTES?.trim(), "READING_PREGEN_SPREAD_MINUTES"],
    [env.READING_SCHEDULER_BATCH_LIMIT?.trim(), "READING_SCHEDULER_BATCH_LIMIT"],
    [callLimit, "READING_DAILY_PROVIDER_CALL_LIMIT"],
    // No OpenAI key, credential mode, gateway id, or BYOK alias appears here.
    // None of them can produce a reading any more, and demanding one would make
    // a deployment look configured for a path that no longer exists.
  ];

  // The Codex posture, required exactly as the ontology pipeline requires it:
  // the runner authenticates with this token, the exchange artifacts are sealed
  // with this keyring, and both live in this bucket. A deployment missing any
  // one of them can create a provider job it can never execute, so it refuses
  // here instead — where the answer is a 503 on the next request rather than a
  // reader's missing reading.
  const runnerToken = env.CODEX_RUNNER_TOKEN?.trim() ?? "";
  if (!/^[A-Za-z0-9._-]{32,512}$/.test(runnerToken)) {
    return misconfigured(
      "CODEX_RUNNER_TOKEN is required when the reading publisher is enabled",
    );
  }
  if ((env.CODEX_PROVIDER_ARTIFACT_KEYRING?.trim() ?? "") === "") {
    return misconfigured(
      "CODEX_PROVIDER_ARTIFACT_KEYRING is required when the reading publisher is enabled",
    );
  }
  if (!env.ARTIFACTS) {
    return misconfigured(
      "ARTIFACTS is required when the reading publisher is enabled",
    );
  }

  const missing = required.filter(([value]) => value === undefined || value === null || value === "");
  if (missing.length > 0) {
    return misconfigured(
      `The reading publisher is enabled but not configured: ${missing
        .map(([, key]) => key)
        .join(", ")}`,
    );
  }

  return {
    ok: true,
    rollout,
    config: {
      pin: {
        provider: READING_PUBLISHER_PROVIDER,
        model: OPENAI_READING_MODEL,
        reasoning_effort: OPENAI_READING_REASONING,
        prompt_version: promptVersion!,
        output_schema: "daily-reading-v5",
        // Filled by the caller that freezes a command; the engine owns both
        // numbers and this pin records which ones a command was built under.
        selection_policy_version: SELECTION_POLICY_VERSION,
        validation_policy_version: VALIDATION_POLICY_VERSION,
        max_output_tokens: OPENAI_READING_MAX_OUTPUT_TOKENS,
        context_max_bytes: READING_CONTEXT_MAX_BYTES,
      },
      timeoutMs: OPENAI_READING_TIMEOUT_MS,
      dailyCallLimit: callLimit!,
      pregenActiveDays: READING_PREGEN_ACTIVE_DAYS,
      pregenLeadMinutes: READING_PREGEN_LEAD_MINUTES,
      pregenSpreadMinutes: READING_PREGEN_SPREAD_MINUTES,
      schedulerBatchLimit: READING_SCHEDULER_BATCH_LIMIT,
    },
  };
}
