import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, posix, relative, resolve, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HASH_DOMAIN = "patternlike.pattern-creation-source.v1";
const HASH_PATTERN = /^sha256:[0-9a-f]{64}$/;

export interface PatternSourceFingerprintOptions {
  root: string;
  manifestPath: string;
  outputPath: string;
}

export interface PatternSourceFingerprint {
  hash: string;
  sources: string[];
}

export class PatternSourceFingerprintError extends Error {
  constructor(readonly code: string) {
    super(code);
    this.name = "PatternSourceFingerprintError";
  }
}

function fail(code: string): never {
  throw new PatternSourceFingerprintError(code);
}

function lengthPrefix(length: number): Buffer {
  const prefix = Buffer.alloc(8);
  prefix.writeBigUInt64BE(BigInt(length));
  return prefix;
}

function validateSourcePath(value: unknown): string {
  if (typeof value !== "string" || value.length === 0) {
    fail("manifest_invalid_path");
  }
  if (isAbsolute(value) || posix.isAbsolute(value)) {
    fail("manifest_absolute_path");
  }
  if (
    value.includes("\\") ||
    value === ".." ||
    value.startsWith("../") ||
    value.includes("/../") ||
    posix.normalize(value) !== value
  ) {
    fail("manifest_traversal_path");
  }
  if (!value.endsWith(".ts") || value.endsWith(".test.ts")) {
    fail("manifest_non-typescript_path");
  }
  if (
    !value.startsWith("apps/api/src/") &&
    !value.startsWith("packages/pattern-engine/src/")
  ) {
    fail("manifest_outside_pattern_source_path");
  }
  return value;
}

async function readManifest(path: string): Promise<string[]> {
  let value: unknown;
  try {
    value = JSON.parse(await readFile(path, "utf8")) as unknown;
  } catch (error) {
    if (error instanceof SyntaxError) fail("manifest_json_invalid");
    fail("manifest_missing");
  }
  if (
    value === null ||
    typeof value !== "object" ||
    Array.isArray(value) ||
    Object.keys(value).length !== 2 ||
    (value as { version?: unknown }).version !== 1 ||
    !Array.isArray((value as { sources?: unknown }).sources) ||
    (value as { sources: unknown[] }).sources.length === 0
  ) {
    fail("manifest_shape_invalid");
  }
  const sources = (value as { sources: unknown[] }).sources.map(validateSourcePath);
  if (new Set(sources).size !== sources.length) {
    fail("manifest_duplicate_path");
  }
  const ordered = [...sources].sort((left, right) => left.localeCompare(right));
  if (sources.some((source, index) => source !== ordered[index])) {
    fail("manifest_unsorted_path");
  }
  return sources;
}

function containedPath(root: string, source: string): string {
  const absoluteRoot = resolve(root);
  const absoluteSource = resolve(absoluteRoot, ...source.split("/"));
  const fromRoot = relative(absoluteRoot, absoluteSource);
  if (fromRoot === "" || fromRoot === ".." || fromRoot.startsWith(`..${sep}`) || isAbsolute(fromRoot)) {
    fail("manifest_traversal_path");
  }
  return absoluteSource;
}

export async function buildPatternSourceFingerprint(
  options: PatternSourceFingerprintOptions,
): Promise<PatternSourceFingerprint> {
  const sources = await readManifest(options.manifestPath);
  const hash = createHash("sha256");
  const domain = Buffer.from(HASH_DOMAIN, "utf8");
  hash.update(lengthPrefix(domain.byteLength));
  hash.update(domain);

  for (const source of sources) {
    const pathBytes = Buffer.from(source, "utf8");
    let fileBytes: Buffer;
    try {
      fileBytes = await readFile(containedPath(options.root, source));
    } catch {
      fail("source_missing");
    }
    hash.update(lengthPrefix(pathBytes.byteLength));
    hash.update(pathBytes);
    hash.update(lengthPrefix(fileBytes.byteLength));
    hash.update(fileBytes);
  }

  const fingerprint = `sha256:${hash.digest("hex")}`;
  if (!HASH_PATTERN.test(fingerprint)) fail("fingerprint_invalid");
  return { hash: fingerprint, sources };
}

export function renderPatternSourceModule(
  fingerprint: PatternSourceFingerprint,
): string {
  if (!HASH_PATTERN.test(fingerprint.hash)) fail("fingerprint_invalid");
  return [
    "/**",
    " * Generated by scripts/generate-pattern-source-fingerprint.ts.",
    " * Do not edit by hand; run `npm run generate:pattern-source -w @patternlike/api`.",
    " */",
    `export const PATTERN_CREATION_SOURCE_HASH = ${JSON.stringify(fingerprint.hash)} as const;`,
    "",
    "export const PATTERN_CREATION_SOURCE_FILES = [",
    ...fingerprint.sources.map((source) => `  ${JSON.stringify(source)},`),
    "] as const;",
    "",
  ].join("\n");
}

export async function checkPatternSourceFingerprint(
  options: PatternSourceFingerprintOptions,
): Promise<boolean> {
  const expected = renderPatternSourceModule(
    await buildPatternSourceFingerprint(options),
  );
  try {
    return await readFile(options.outputPath, "utf8") === expected;
  } catch {
    return false;
  }
}

export async function writePatternSourceFingerprint(
  options: PatternSourceFingerprintOptions,
): Promise<PatternSourceFingerprint> {
  const fingerprint = await buildPatternSourceFingerprint(options);
  await mkdir(dirname(options.outputPath), { recursive: true });
  await writeFile(options.outputPath, renderPatternSourceModule(fingerprint));
  return fingerprint;
}

function defaultOptions(): PatternSourceFingerprintOptions {
  const scriptPath = fileURLToPath(import.meta.url);
  const root = resolve(dirname(scriptPath), "../../..");
  return {
    root,
    manifestPath: resolve(root, "apps/api/pattern-creation-sources.json"),
    outputPath: resolve(root, "apps/api/src/generated/pattern-creation-source.ts"),
  };
}

export async function runPatternSourceFingerprintCli(
  args: readonly string[],
  output: { stdout(line: string): void; stderr(line: string): void },
): Promise<number> {
  if (args.length !== 1 || (args[0] !== "--write" && args[0] !== "--check")) {
    output.stderr("usage: --write | --check");
    return 2;
  }
  try {
    if (args[0] === "--check") {
      const current = await checkPatternSourceFingerprint(defaultOptions());
      output[current ? "stdout" : "stderr"](
        current ? "PASS pattern_source_fingerprint_current" : "FAIL pattern_source_fingerprint_stale",
      );
      return current ? 0 : 1;
    }
    const written = await writePatternSourceFingerprint(defaultOptions());
    output.stdout(`PASS pattern_source_hash=${written.hash} sources=${written.sources.length}`);
    return 0;
  } catch (error) {
    output.stderr(
      `FAIL ${
        error instanceof PatternSourceFingerprintError
          ? error.code
          : "pattern_source_fingerprint_failed"
      }`,
    );
    return 1;
  }
}

const invokedPath = process.argv[1];
if (invokedPath && import.meta.url === pathToFileURL(resolve(invokedPath)).href) {
  process.exitCode = await runPatternSourceFingerprintCli(process.argv.slice(2), {
    stdout: (line) => console.log(line),
    stderr: (line) => console.error(line),
  });
}
