import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import Ajv2020, { type AnySchemaObject, type Options } from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import addFormats from "ajv-formats";
import { build } from "esbuild";
import { ONTOLOGY_STRICT_SCHEMA } from "../src/services/ontology-output-schemas.js";

const apiRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const contractsRoot = resolve(apiRoot, "../../contracts");
const outputRoot = resolve(apiRoot, "src/generated");
const banner = "// Generated by npm run generate:validators -w @patternlike/api. Do not edit.\n";

interface ValidatorGroup {
  name: string;
  strict: boolean;
  formats: boolean;
  schemas: readonly string[];
  validators: Record<string, string>;
  types: string;
  extraSchemas?: Record<string, AnySchemaObject>;
}

// Preserve each former compiler's strictness, format behavior and exact $ref.
// The JSON contracts and shared provider schema objects remain authoritative.
const groups: readonly ValidatorGroup[] = [
  {
    name: "reading-validators",
    strict: false,
    formats: true,
    schemas: [
      "m0/common", "m3/common", "m5/common", "m5/daily-reading",
      "m5/reading-evidence", "m5/reading-generation-output",
    ],
    validators: {
      validateReadingOutput: "m5/reading-generation-output",
      validateTodayResponseV5: "m5/daily-reading#/$defs/dailyReadingResponseV5",
      validateEvidenceGraphV5: "m5/reading-evidence#/$defs/readingEvidenceGraphV5",
    },
    types: `import type { ValidateFunction } from "ajv";
import type { ReadingGenerationOutput } from "@patternlike/shared";
export declare const validateReadingOutput: ValidateFunction<ReadingGenerationOutput>;
export declare const validateTodayResponseV5: ValidateFunction;
export declare const validateEvidenceGraphV5: ValidateFunction;
`,
  },
  {
    name: "strict-validators",
    strict: true,
    formats: true,
    schemas: [
      "m0/common", "m0/content-release", "m3/common", "m3/content-release",
      "m4/common", "m4/natal-feature", "m4/content-release", "m7/common",
      "m7/pattern-source-fragment", "m7/pattern-source-corpus-release",
      "m7/pattern-ontology-record", "m7/pattern-ontology-evaluation",
      "m7/pattern-ontology-release", "m7/pattern-erasure-replay-event",
      "m9/common", "m9/pattern-regeneration-replay-event",
    ],
    validators: {
      validateContentReleaseV3: "m3/content-release#/$defs/contentReleaseIngestionRequest",
      validateContentReleaseV4: "m4/content-release#/$defs/contentReleaseIngestionRequest",
      validateSourceCorpusRelease: "m7/pattern-source-corpus-release#/$defs/patternSourceCorpusRelease",
      validateOntologyRelease: "m7/pattern-ontology-release",
      validateNatalPredicate: "m4/natal-feature#/$defs/natalPredicate",
      validateReplayEvent: "m7/pattern-erasure-replay-event",
      validateRegenerationReplayEvent: "m9/pattern-regeneration-replay-event",
    },
    types: `import type { ValidateFunction } from "ajv";
import type {
  PatternOntologyRelease, PatternOntologyRecord,
  PatternErasureReplayEvent, PatternRegenerationReplayEvent,
} from "@patternlike/shared";
import type { ContentReleaseIngestionRequest } from "../services/content-release.js";
export declare const validateContentReleaseV3: ValidateFunction<ContentReleaseIngestionRequest>;
export declare const validateContentReleaseV4: ValidateFunction<ContentReleaseIngestionRequest>;
export declare const validateSourceCorpusRelease: ValidateFunction;
export declare const validateOntologyRelease: ValidateFunction<PatternOntologyRelease>;
export declare const validateNatalPredicate: ValidateFunction<PatternOntologyRecord["feature_predicate"]>;
export declare const validateReplayEvent: ValidateFunction<PatternErasureReplayEvent>;
export declare const validateRegenerationReplayEvent: ValidateFunction<PatternRegenerationReplayEvent>;
`,
  },
  {
    name: "ontology-output-validators",
    strict: true,
    formats: false,
    schemas: [],
    extraSchemas: {
      generator: ONTOLOGY_STRICT_SCHEMA.generator as AnySchemaObject,
      evaluator: ONTOLOGY_STRICT_SCHEMA.evaluator as AnySchemaObject,
    },
    validators: {
      validateOntologyGenerationChunk: "generator",
      validateOntologyRuleVerdict: "evaluator",
    },
    types: `import type { ValidateFunction } from "ajv";
import type { OntologyGenerationChunk, OntologyRuleVerdict } from "../services/ontology-publisher.js";
export declare const validateOntologyGenerationChunk: ValidateFunction<OntologyGenerationChunk>;
export declare const validateOntologyRuleVerdict: ValidateFunction<OntologyRuleVerdict>;
`,
  },
];

export async function generateWorkerValidators(): Promise<Map<string, string>> {
  const files = new Map<string, string>();
  for (const group of groups) {
    const options: Options = {
      strict: group.strict,
      code: { source: true, esm: true, lines: true },
    };
    const ajv = new Ajv2020(options);
    if (group.formats) addFormats(ajv);
    const ids = new Map<string, string>();
    for (const name of group.schemas) {
      const schema = JSON.parse(await readFile(resolve(contractsRoot, `${name}.schema.json`), "utf8")) as AnySchemaObject;
      if (typeof schema.$id !== "string") throw new Error(`Schema ID missing: ${name}`);
      ids.set(name, schema.$id);
      ajv.addSchema(schema);
    }
    for (const [name, schema] of Object.entries(group.extraSchemas ?? {})) {
      ids.set(name, name);
      ajv.addSchema(schema, name);
    }
    const exports = Object.fromEntries(Object.entries(group.validators).map(([name, reference]) => {
      const [document, fragment] = reference.split("#");
      const id = ids.get(document!);
      if (!id) throw new Error(`Schema registration missing: ${reference}`);
      return [name, id + (fragment === undefined ? "" : `#${fragment}`)];
    }));
    // Bundle Ajv's tiny static runtime/format helpers too. The Worker needs no
    // compiler, CommonJS require, eval, or new Function at import or invocation.
    const compiled = await build({
      absWorkingDir: apiRoot,
      stdin: { contents: standaloneCode(ajv, exports), resolveDir: apiRoot },
      bundle: true,
      format: "esm",
      platform: "browser",
      target: "es2022",
      write: false,
      legalComments: "inline",
    });
    const output = compiled.outputFiles[0]?.text;
    if (!output) throw new Error(`Validator output missing: ${group.name}`);
    files.set(`${group.name}.js`, banner + output);
    files.set(`${group.name}.d.ts`, banner + group.types);
  }
  return files;
}

async function main(): Promise<void> {
  const mode = process.argv[2];
  if (process.argv.length !== 3 || (mode !== "--write" && mode !== "--check")) {
    throw new Error("Use --write or --check");
  }
  const files = await generateWorkerValidators();
  if (mode === "--write") await mkdir(outputRoot, { recursive: true });
  for (const [name, content] of files) {
    const target = resolve(outputRoot, name);
    if (mode === "--write") {
      await writeFile(target, content);
    } else {
      const current = await readFile(target, "utf8").catch(() => null);
      if (current?.replace(/\r\n/g, "\n") !== content) {
        throw new Error(`Generated validator is stale: ${name}. Run generate:validators.`);
      }
    }
  }
  console.log(`Worker validators ${mode === "--write" ? "generated" : "verified"}: ${files.size} files`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : "Validator generation failed");
    process.exitCode = 1;
  });
}
